### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by megangaw** [HT-M-L/web-app#43]

**Comment by megangaw** [comment]
Success: We were able to get a start to our coding and create some basic layouts for the pages, with a couple set back in the main code we managed to get a lot done. I was able to get 2 pages mostly done and look over everyone else code as they went along.

Failures: got a late start in the week, if we had started a couple days earlier we could have gotten some more done.

**Comment by laurenberg** [comment]
SUCCESS: We built a strong foundation this week. I set up Jekyll files and finished branding based on peer feedback, exporting web friendly files for us to start working with. Created a basic navigation and footer in Jekyll styles.
FAILURES: We had some friction with the .DS_Store and _site files while working in a group through Github, Thomas was able to fix this for us and our best conclusion is maybe we weren't pulling from the master before coding/committing.

**Comment by sashatran95** [comment]
**Sprint Success:**
Completed a wireframe prototype on XD file and added codes on the html file of an assigned page.

**Sprint Failure:**
Ran into issues with Github caused by creating pull requests on a master branch, and using a super outdated Github desktop app. Problem solved.
Could be more competent and be more useful in the group.

**Comment by laurenberg** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Great work on the Sprint reviews!

- The Project boards are well set up but the Issues need much more information, the title isn’t enough.
